[package]
name = "nanorod"
version = "0.1.0"
edition = "2024"

[features]
default = []
gpu = ["dep:cudarc"]

[[bin]]
name = "nanorod"
path = "src/main.rs"
required-features = ["gpu"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.6.1", features = ["derive"] }
csv = "1.4.0"
cudarc = { version = "0.19.7", default-features = false, features = [
  "std",
  "driver",
  "nvrtc",
  "dynamic-loading",
  "cuda-12020",
], optional = true }
eframe = { version = "0.34.3", default-features = false, features = [
  "default_fonts",
  "glow",
  "wayland",
  "x11",
] }
egui = "0.34.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
